apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis
  namespace: klns-administration
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: rds.kubelilin.com:6379  # Redis主机和端口号
    - name: redisPassword
      value: ""  # Redis密码（可选）