apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-server
  labels:
    app: myapp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: myapp-server
  template:
    metadata:
      labels:
        k8s-app: myapp-server
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprclient-daprdemos-kind-kind" # app-id, 使用PasS部署的话 取部署名称
        dapr.io/app-port: "8223"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: app
          image: kubelilin/dapr_demos:server_v0.2
