apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-server
  labels:
    app: state-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: state-server
  template:
    metadata:
      labels:
        k8s-app: state-server
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "state-server"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: app
          image: kubelilin/dapr_demos:state_server_v0.2

---
apiVersion: v1
kind: Service
metadata:
  name: state-server
spec:
  selector:
    k8s-app: state-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000